# Generated by Django 2.0.5 on 2019-11-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20191117_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(blank=True, max_length=100)),
                ('encripted', models.CharField(blank=True, max_length=100)),
                ('original_crc', models.IntegerField(default=0)),
            ],
        ),
    ]
