# Generated by Django 2.0.5 on 2019-11-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chanel',
        ),
        migrations.DeleteModel(
            name='names',
        ),
    ]
